### ISSUE TITLE
Erreur - Utilisation du curseur MySQL

### ISSUE THREAD

**Issue by tarturr** [tarturr/DiscordIn#7]
Lors du démarrage de la commande ``reset-db`` qui ouvre donc une connexion à la base de données, on obtient l'erreur suivante :
```
> flask --app pandamonium reset-db
[PANDAMONIUM] Successfully connected to database!
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Documents\Projects\PycharmProjects\PANDAMONIUM\.venv\Scripts\flask.exe\__main__.py", line 7, in <module>
  File "D:\Documents\Projects\PycharmProjects\PANDAMONIUM\.venv\Lib\site-packages\flask\cli.py", line 1107, in main
    cli.main()
  File "D:\Documents\Projects\PycharmProjects\PANDAMONIUM\.venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "D:\Documents\Projects\PycharmProjects\PANDAMONIUM\.venv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\Projects\PycharmProjects\PANDAMONIUM\.venv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\Projects\PycharmProjects\PANDAMONIUM\.venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\Projects\PycharmProjects\PANDAMONIUM\.venv\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\Projects\PycharmProjects\PANDAMONIUM\.venv\Lib\site-packages\flask\cli.py", line 388, in decorator
    return ctx.invoke(f, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\Projects\PycharmProjects\PANDAMONIUM\.venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\Projects\PycharmProjects\PANDAMONIUM\pandamonium\commands.py", line 19, in reset_db
    db.init_db(set_default_values=dev)
  File "D:\Documents\Projects\PycharmProjects\PANDAMONIUM\pandamonium\db.py", line 36, in init_db
    db.commit()
  File "D:\Documents\Projects\PycharmProjects\PANDAMONIUM\.venv\Lib\site-packages\mysql\connector\connection_cext.py", line 532, in commit
    self._cmysql.commit()
_mysql_connector.MySQLInterfaceError: Commands out of sync; you can't run this command now
```
D'après [ce post StackOverflow](https://stackoverflow.com/questions/11583083/python-mysql-commands-out-of-sync-you-cant-run-this-command-now), l'erreur pourrait être liée aux faits suivants :
- On ne ferme pas le curseur avant d'exécuter une autre requête SQL ;
- On ne vide pas le résultat de la requête ;
- L'exécution des fonctions est faite dans le mauvais ordre.

**Comment by tarturr** [comment]
Le problème a été réglé dans le commit [f550d90](https://github.com/tarturr/PANDAMONIUM/commit/f550d90df8f7f909e36ee56f10c4bc6f6168c94c), en mettant chaque instruction SQL en une seule ligne afin que le module MySQL de Python exécute les requêtes ligne par ligne.
